# Generated by Django 3.2.7 on 2021-11-15 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_roomchat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chat',
        ),
    ]
