# Generated by Django 3.2.7 on 2021-11-15 19:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapi', '0006_userschat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usersChat',
            new_name='userChat',
        ),
    ]
