# Generated by Django 3.2.7 on 2021-11-22 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_rename_userschat_userchat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='maximum_players',
        ),
        migrations.AddField(
            model_name='room',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapi.game'),
            preserve_default=False,
        ),
    ]
